title: "Homelab – dokumentacja"
description: "Dokumentacja mojego homelabu"
theme: minima

author:
  name: "Lem00rek"
  email: ""

# Strony, które pojawią się w górnym menu
header_pages:
  - sprzet.md
  - siec.md
  - uslugi.md
  - backupy.md
  - configi.md
